/**
 * Video SEO Pages — full landing pages with an embedded self-hosted video +
 * VideoObject schema, so posso.co.uk ranks in Google Video on its own domain.
 * Merged into allSeoPages and rendered by (seo-pages)/[slug]/page.tsx.
 * Video assets: /public/videos/<slug>.mp4 + /public/videos/thumbs/<slug>.png
 */
import type { SeoPageData } from './seo-pages-data';

const DUR = { durationSec: 39, durationISO: 'PT39S', uploadDate: '2026-07-14' };
const STD_CHAPTERS = (s1: string) => [
  { name: 'Intro', start: 0 },
  { name: s1, start: 5 },
  { name: 'Kiosk features', start: 14 },
  { name: 'The numbers', start: 26 },
  { name: 'Book a demo', start: 32 },
];

export const videoPages: SeoPageData[] = [
  {
    slug: 'outdoor-self-order-kiosks-food-truck-epos',
    title: 'Outdoor Self-Order Kiosks & Food Truck EPOS | Posso',
    description: 'IP65 weatherproof, water-resistant self-order kiosks and food truck EPOS from Posso. Built for the outdoors — watch the video and book a demo.',
    h1: 'Outdoor Self-Order Kiosks & Food Truck EPOS',
    subtitle: 'IP65 weatherproof self-order kiosks and compact 4G food truck EPOS — built to trade outdoors in British weather.',
    category: 'kiosk',
    targetKeyword: 'outdoor self order kiosk',
    heroContent: 'Trading outdoors? Posso self-order kiosks are IP65 water-resistant and built to survive British weather, with bright, sunlight-readable touchscreens that take orders and payments while your team cooks. Paired with Posso’s compact 4G food truck EPOS, you serve faster, cut queues and lift average order value with automatic upsells.',
    sections: [
      { heading: 'Built for the Outdoors', content: 'Most self-order kiosks are indoor units that fail the moment they meet rain or direct sun. Posso outdoor kiosks are IP65 rated — dust-tight and protected against water jets — with high-brightness, sunlight-readable screens and a secure, weather-sealed enclosure. Deploy them at markets, festivals, stadiums, food trucks and beer gardens, all year round.' },
      { heading: 'Food Truck EPOS That Goes Anywhere', content: 'Posso’s food truck EPOS is compact and runs on 4G, so you can take chip, contactless and mobile payments with no fixed Wi-Fi. It doubles as your till, prints or sends orders to the kitchen, and shows live sales and stock on your phone — everything a mobile trader needs in one box.' },
      { heading: 'Serve Faster, Sell More', content: 'Self-service means shorter queues, fewer mistakes and a consistent upsell on every order. Operators typically see around a 30% lift in average order value once customers order at their own pace with prompts for sides, drinks and meal deals.' },
    ],
    features: [
      { title: 'IP65 Weatherproof', desc: 'Water and dust resistant housing rated for permanent outdoor use.' },
      { title: 'Sunlight-Readable Screen', desc: 'High-brightness touchscreen that stays clear in direct sun.' },
      { title: 'Self-Service Ordering', desc: 'Shorter queues and less labour — customers order and pay themselves.' },
      { title: 'Automatic Upsells', desc: 'Prompts for sides, drinks and meal deals on every order.' },
      { title: '4G Food Truck EPOS', desc: 'Compact all-in-one till with card payments, no fixed Wi-Fi needed.' },
      { title: 'Live Sales & Stock', desc: 'Track takings and stock in real time from your phone.' },
    ],
    faqs: [
      { q: 'Are Posso self-order kiosks suitable for outdoor use?', a: 'Yes. Posso outdoor kiosks are IP65 rated — water and dust resistant — with sunlight-readable screens, so they work in rain, sun and cold.' },
      { q: 'Do the kiosks and EPOS work without Wi-Fi?', a: 'Yes. Posso food truck EPOS and kiosks run on 4G, so you can take orders and card payments anywhere, even with no fixed internet.' },
      { q: 'Can a self-order kiosk increase my average order value?', a: 'Self-order typically lifts average order value by around 30% through consistent, no-pressure upsells on every order.' },
    ],
    ctaHeading: 'Take Your Kiosk Outdoors',
    ctaText: 'Book a free demo of Posso’s IP65 outdoor self-order kiosks and food truck EPOS — built for British weather.',
    relatedSlugs: ['outdoor-self-order-kiosks-ip65', 'self-order-kiosk-cost', 'do-self-order-kiosks-increase-sales'],
    video: { ...DUR, chapters: [
      { name: 'Built for food trucks & the outdoors', start: 0 },
      { name: 'Food truck EPOS', start: 5 },
      { name: 'Outdoor water-resistant self-order kiosks', start: 16 },
      { name: '+30% average order value', start: 30 },
      { name: 'Book a demo', start: 34 },
    ], transcript: 'Trading outdoors? Posso self-order kiosks are IP65 water-resistant and built for British weather, with sunlight-readable touchscreens. Paired with a compact 4G food truck EPOS — all-in-one till plus card payments — you serve faster, cut queues and lift average order value by around 30% with automatic upsells. Book a demo at posso.co.uk.' },
  },
  {
    slug: 'self-order-kiosk-cost',
    title: 'How Much Does a Self-Order Kiosk Cost? UK | Posso',
    description: 'Self-order kiosk cost explained: what’s included, pricing and how fast a kiosk pays for itself. Watch the video and see Posso kiosk pricing.',
    h1: 'How Much Does a Self-Order Kiosk Cost?',
    subtitle: 'What’s included in a self-order kiosk, what it costs and how quickly it pays for itself.',
    category: 'kiosk',
    targetKeyword: 'self order kiosk cost',
    heroContent: 'How much does a self-order kiosk cost in the UK? It depends on hardware, software and support — but the more useful question is how fast it pays back. This video breaks down what’s included and the ROI: lower staff cost per order, bigger average orders and more covers at peak.',
    sections: [
      { heading: 'What You Actually Pay For', content: 'A self-order kiosk price covers the touchscreen hardware, the ordering software and menu, integrated card payments, and installation with UK support. Posso quotes the full picture transparently — upfront hardware and the monthly software licence — so there are no surprises. Costs scale with the number of kiosks and whether you want floor-standing or wall-mounted units.' },
      { heading: 'How a Kiosk Pays for Itself', content: 'The right question isn’t “how much” but “how fast does it pay back”. Kiosks lower staff cost per order, lift average order value by around 30% through consistent upsells, reduce mistakes and refunds, and let you serve more covers at peak without hiring. Many venues see payback within months.' },
    ],
    features: [
      { title: 'Touchscreen Hardware', desc: 'Floor-standing or wall-mounted kiosk units built for busy venues.' },
      { title: 'Ordering Software & Menu', desc: 'Full menu build, images, modifiers and upsell prompts included.' },
      { title: 'Card Payments Built In', desc: 'Chip, contactless and mobile payments taken at the kiosk.' },
      { title: 'Install & UK Support', desc: 'Setup, menu programming and ongoing UK-based support.' },
      { title: 'Fast Payback', desc: 'Lower labour per order and bigger baskets typically pay back in months.' },
      { title: 'Scales With You', desc: 'Add kiosks as you grow — one price model across your sites.' },
    ],
    faqs: [
      { q: 'How much does a self-order kiosk cost in the UK?', a: 'Cost varies by hardware, software and support. Posso offers tailored pricing — book a demo for a quote based on your setup and number of kiosks.' },
      { q: 'Do self-order kiosks have a monthly fee?', a: 'Most kiosk setups include a software and support subscription. Posso quotes the full monthly and upfront cost transparently.' },
      { q: 'How quickly does a self-order kiosk pay for itself?', a: 'Many venues see payback in months through lower labour cost per order, bigger average orders and fewer mistakes.' },
    ],
    ctaHeading: 'Get Your Self-Order Kiosk Quote',
    ctaText: 'Book a free demo and get transparent pricing for Posso self-order kiosks, tailored to your venue.',
    relatedSlugs: ['self-order-kiosks-for-restaurants', 'do-self-order-kiosks-increase-sales', 'outdoor-self-order-kiosks-ip65'],
    video: { ...DUR, chapters: STD_CHAPTERS("What's included"), transcript: 'How much does a self-order kiosk cost? Pricing covers the touchscreen hardware, ordering software, card payments and install with UK support. The real value is ROI: lower staff cost per order, bigger average orders, fewer refunds and more covers at peak — so a kiosk typically pays for itself within months. Book a demo at posso.co.uk.' },
  },
  {
    slug: 'self-order-kiosks-for-restaurants',
    title: 'Self-Order Kiosks for Restaurants UK | Posso',
    description: 'Self-order kiosks for restaurants — more covers, shorter queues and higher spend. Watch how Posso kiosks work and book a demo.',
    h1: 'Self-Order Kiosks for Restaurants',
    subtitle: 'Serve more covers with the same team — shorter queues, fewer mistakes and higher average spend.',
    category: 'kiosk',
    targetKeyword: 'self order kiosk for restaurants',
    heroContent: 'Self-order kiosks help restaurants serve more covers with the same team. Cut queues at busy times, free staff to serve and cook, reduce order mistakes, and lift average spend with automatic upsells and meal deals — all integrated with your kitchen.',
    sections: [
      { heading: 'Why Restaurants Switch to Kiosks', content: 'At peak, every minute a customer spends queuing is a lost cover. Self-order kiosks let guests order and pay themselves, so your team focuses on food and service instead of taking orders. Orders are accurate, upsells are consistent, and throughput climbs without adding staff.' },
      { heading: 'Integrated With Your Kitchen and EPOS', content: 'Posso kiosks aren’t a bolt-on — they’re part of the same system as your tills and online ordering. Kiosk orders fire straight to the kitchen display or printer and appear alongside every other order, so you have one menu, one stock count and one source of truth for reporting.' },
    ],
    features: [
      { title: 'Cut Queues at Peak', desc: 'More covers served per hour without hiring extra staff.' },
      { title: 'Fewer Order Mistakes', desc: 'Customers confirm their own order — accuracy goes up, refunds go down.' },
      { title: 'Automatic Upsells', desc: 'Meal deals, sides and drinks suggested on every order.' },
      { title: 'Kitchen Integration', desc: 'Orders route straight to your KDS or kitchen printer.' },
      { title: 'One Unified System', desc: 'Kiosk, till and online orders on one menu and dashboard.' },
      { title: 'Card & Contactless', desc: 'Payments taken at the kiosk — chip, contactless and mobile.' },
    ],
    faqs: [
      { q: 'Do self-order kiosks work for full-service restaurants?', a: 'Yes — kiosks handle counter, collection and quick-service ordering, freeing staff for table service and reducing queues at peak.' },
      { q: 'Do kiosks integrate with the kitchen?', a: 'Yes. Posso kiosks send orders straight to the kitchen display or printer and your EPOS, keeping service fast and accurate.' },
      { q: 'Will a kiosk increase my average order value?', a: 'Typically by around 30%, because guests browse at their own pace and every order includes consistent upsell prompts.' },
    ],
    ctaHeading: 'Bring Kiosks to Your Restaurant',
    ctaText: 'Book a free demo of Posso self-order kiosks for restaurants — more covers, higher spend, happier guests.',
    relatedSlugs: ['self-order-kiosks-for-takeaways', 'self-order-kiosk-cost', 'do-self-order-kiosks-increase-sales'],
    video: { ...DUR, chapters: STD_CHAPTERS('Why restaurants switch'), transcript: 'Self-order kiosks help restaurants serve more covers with the same team. Cut queues at busy times, free staff to serve and cook, reduce mistakes, and lift average spend with automatic upsells and meal deals — all integrated with your kitchen and EPOS. Book a demo at posso.co.uk.' },
  },
  {
    slug: 'self-order-kiosks-for-takeaways',
    title: 'Self-Order Kiosks for Takeaways UK | Posso',
    description: 'Self-order kiosks for takeaways — take more orders with less staff. Watch how Posso takeaway kiosks work and book a demo.',
    h1: 'Self-Order Kiosks for Takeaways',
    subtitle: 'Handle the rush without hiring — no missed orders, an upsell on every ticket, straight to the kitchen.',
    category: 'kiosk',
    targetKeyword: 'self order kiosk for takeaway',
    heroContent: 'Self-order kiosks let takeaways handle the rush without hiring more staff. No missed phone orders, an upsell on every order, and tickets that print straight to the kitchen — with card and contactless payments and live reporting.',
    sections: [
      { heading: 'Perfect for the Takeaway Rush', content: 'Friday night is when takeaways make their money — and when staff are stretched thinest. A self-order kiosk absorbs walk-in demand: customers order and pay at the screen, tickets fire to the kitchen instantly, and no order is missed because someone couldn’t get to the counter or phone.' },
      { heading: 'More Per Order, Less Labour', content: 'Every kiosk order offers sides, drinks and deals automatically, so baskets grow. At the same time, self-service lowers your labour cost per order and frees staff to prep and pack. It’s more revenue and lower cost from the same footprint.' },
    ],
    features: [
      { title: 'Handle Rushes', desc: 'Absorb peak walk-in demand without adding staff.' },
      { title: 'No Missed Orders', desc: 'Every order is captured at the screen — nothing lost at the counter.' },
      { title: 'Upsell Every Ticket', desc: 'Sides, drinks and meal deals offered on every order.' },
      { title: 'Prints to Kitchen', desc: 'Orders route straight to your kitchen printer or display.' },
      { title: 'Collection & Eat-In', desc: 'Modes for collection and dine-in from the same kiosk.' },
      { title: 'Card & Contactless', desc: 'Fast payments taken at the kiosk with live reporting.' },
    ],
    faqs: [
      { q: 'Are self-order kiosks good for takeaways?', a: 'Yes — kiosks handle peak rushes without extra staff, remove missed phone orders and upsell on every order.' },
      { q: 'Can customers pay at the kiosk?', a: 'Yes. Posso kiosks take card and contactless payments and send the order straight to the kitchen.' },
      { q: 'Does the kiosk print to the kitchen?', a: 'Yes — kiosk orders route to your kitchen printer or display automatically, alongside walk-in and online orders.' },
    ],
    ctaHeading: 'Speed Up Your Takeaway',
    ctaText: 'Book a free demo of Posso self-order kiosks for takeaways — more orders, less queue, straight to the kitchen.',
    relatedSlugs: ['self-order-kiosks-for-restaurants', 'do-self-order-kiosks-increase-sales', 'self-order-kiosk-cost'],
    video: { ...DUR, chapters: STD_CHAPTERS('Perfect for takeaways'), transcript: 'Self-order kiosks let takeaways handle the rush without hiring more staff. No missed phone orders, an upsell on every order, and tickets that print straight to the kitchen — with card and contactless payments and live reporting. Book a demo at posso.co.uk.' },
  },
  {
    slug: 'outdoor-self-order-kiosks-ip65',
    title: 'Outdoor Self-Order Kiosks — IP65 Weatherproof | Posso',
    description: 'IP65 weatherproof outdoor self-order kiosks built for British weather. Water & dust resistant, sunlight-readable, 4G. Watch the video and book a demo.',
    h1: 'Outdoor Self-Order Kiosks (IP65 Weatherproof)',
    subtitle: 'IP65 water and dust resistant, sunlight-readable and 4G — self-order kiosks that trade anywhere outside.',
    category: 'kiosk',
    targetKeyword: 'outdoor self order kiosk',
    heroContent: 'Posso outdoor self-order kiosks are IP65 rated — water and dust resistant — with a sunlight-readable screen and a secure, tough build that works in rain, sun and cold. Perfect for stadiums, markets, festivals, food trucks and beer gardens, running on 4G with card payments built in.',
    sections: [
      { heading: 'What IP65 Means for You', content: 'IP65 is an ingress-protection rating: the “6” means fully dust-tight, and the “5” means protected against low-pressure water jets from any direction. In plain terms, a Posso outdoor kiosk shrugs off rain, spray, dust and grime — so it keeps trading through a British summer or a winter market.' },
      { heading: 'Trade Anywhere Outside', content: 'Because they run on 4G with card payments built in, outdoor kiosks don’t need fixed Wi-Fi or mains data. Drop them at a stadium concourse, a festival pitch, a beer garden or beside a food truck and start taking self-service orders in minutes.' },
    ],
    features: [
      { title: 'IP65 Rated', desc: 'Dust-tight and protected against water jets from any direction.' },
      { title: 'Sunlight-Readable', desc: 'High-brightness screen stays clear in direct sun.' },
      { title: 'All-Weather Build', desc: 'Works in rain, sun and cold with a secure, tough enclosure.' },
      { title: '4G Connectivity', desc: 'No fixed Wi-Fi needed — trade anywhere outdoors.' },
      { title: 'Card Payments Built In', desc: 'Chip, contactless and mobile payments at the kiosk.' },
      { title: 'Fast to Deploy', desc: 'Set up at events, markets and venues in minutes.' },
    ],
    faqs: [
      { q: 'What does IP65 mean for an outdoor kiosk?', a: 'IP65 means the kiosk is dust-tight and protected against low-pressure water jets from any direction — suitable for permanent outdoor use in British weather.' },
      { q: 'Where can outdoor self-order kiosks be used?', a: 'Stadiums, markets, festivals, food trucks, beer gardens and any outdoor venue — they run on 4G so no fixed Wi-Fi is needed.' },
      { q: 'Can outdoor kiosks take payments?', a: 'Yes — card, contactless and mobile payments are built in, and orders route straight to your kitchen or prep station.' },
    ],
    ctaHeading: 'Take Orders Outdoors, Whatever the Weather',
    ctaText: 'Book a free demo of Posso IP65 outdoor self-order kiosks — built for British weather.',
    relatedSlugs: ['outdoor-self-order-kiosks-food-truck-epos', 'self-order-kiosk-cost', 'do-self-order-kiosks-increase-sales'],
    video: { ...DUR, chapters: [
      { name: 'Intro', start: 0 },
      { name: 'Made for outdoors', start: 5 },
      { name: 'Trade anywhere outside', start: 14 },
      { name: 'IP65 rated', start: 26 },
      { name: 'Book a demo', start: 32 },
    ], transcript: 'Posso outdoor self-order kiosks are IP65 rated — water and dust resistant — with a sunlight-readable screen and a tough, secure build that works in rain, sun and cold. They run on 4G with card payments built in, so you can trade at stadiums, markets, festivals, food trucks and beer gardens. Book a demo at posso.co.uk.' },
  },
  {
    slug: 'do-self-order-kiosks-increase-sales',
    title: 'Do Self-Order Kiosks Increase Sales? UK | Posso',
    description: 'Do self-order kiosks really increase sales? The numbers behind self-order — bigger baskets, consistent upsells and shorter queues. Watch and book a demo.',
    h1: 'Do Self-Order Kiosks Increase Sales?',
    subtitle: 'The numbers behind self-order — why average spend rises and queues fall.',
    category: 'kiosk',
    targetKeyword: 'do self order kiosks increase sales',
    heroContent: 'Do self-order kiosks really increase sales? The evidence says yes. With no pressure, guests browse more; every combo and side is offered; baskets grow and upsells are consistent on every order. Add shorter queues and lower labour cost per order and the numbers stack up.',
    sections: [
      { heading: 'Why Average Spend Goes Up', content: 'When customers order from a screen at their own pace, they add more — there’s no queue behind them and no member of staff to rush past. Every item can carry a prompt for a side, a drink or an upgrade, and those prompts fire consistently on every single order. The result is a reliable uplift in average order value, commonly around 30%.' },
      { heading: 'More Than Just Bigger Baskets', content: 'Kiosks don’t only grow the average order — they serve more customers per hour by cutting queues, they lower labour cost per order, and they reduce mistakes and refunds. Together that means more revenue and lower cost from the same space and team.' },
    ],
    features: [
      { title: 'No-Pressure Browsing', desc: 'Guests take their time and add more to the basket.' },
      { title: 'Consistent Upsells', desc: 'Every order offers sides, drinks and upgrades — automatically.' },
      { title: '~30% Higher Spend', desc: 'Typical uplift in average order value with self-order.' },
      { title: 'Shorter Queues', desc: 'Serve more customers per hour at peak.' },
      { title: 'Lower Labour Cost', desc: 'Self-service reduces cost per order.' },
      { title: 'Fewer Mistakes', desc: 'Customer-confirmed orders cut errors and refunds.' },
    ],
    faqs: [
      { q: 'Do self-order kiosks increase average order value?', a: 'Yes — self-order typically lifts average order value by around 30% through consistent, no-pressure upsells on every order.' },
      { q: 'Besides sales, what else do kiosks improve?', a: 'Shorter queues serve more customers, labour cost per order falls, and order accuracy improves — reducing refunds and waste.' },
      { q: 'How soon do the results show?', a: 'Most venues see higher average orders and shorter queues immediately, with the kiosk paying back within months.' },
    ],
    ctaHeading: 'See the Sales Uplift for Yourself',
    ctaText: 'Book a free demo of Posso self-order kiosks and see how they grow average order value and speed up service.',
    relatedSlugs: ['self-order-kiosk-cost', 'self-order-kiosks-for-restaurants', 'self-order-kiosks-for-takeaways'],
    video: { ...DUR, chapters: STD_CHAPTERS('Why spend goes up'), transcript: 'Do self-order kiosks really increase sales? Yes. With no pressure, guests browse more; every combo and side is offered; baskets grow and upsells are consistent on every order. Add shorter queues and lower labour cost per order, and average spend rises by around 30%. Book a demo at posso.co.uk.' },
  },
];
