
import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'www.posso.co.uk',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'plus.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'allguardweb.on-forge.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'sp-ao.shortpixel.ai',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'uk.clover.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'framerusercontent.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'a.storyblok.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
  async redirects() {
    return [
      { source: '/home', destination: '/', permanent: true },
      { source: '/kiosks', destination: '/self-order-kiosks', permanent: true },
      { source: '/best-food-on-the-table-app-by-posso-ltd-uk', destination: '/restaurant-order-at-table-app', permanent: true },
      { source: '/best-restaurant-order-at-table-app-by-posso-ltd-uk', destination: '/restaurant-order-at-table-app', permanent: true },
      { source: '/best-food-ordering-system-by-posso-ltd-uk', destination: '/food-ordering-system', permanent: true },
      { source: '/best-pub-pos-by-posso-ltd-uk', destination: '/pub-pos-system', permanent: true },
      { source: '/best-coffee-ordering-app-by-posso-ltd-uk', destination: '/coffee-ordering-app', permanent: true },
      { source: '/best-hotel-epos-systems-by-posso-ltd-uk', destination: '/hotel-epos-system', permanent: true },
      { source: '/best-self-ordering-kiosks-by-posso-ltd-uk', destination: '/self-ordering-kiosk', permanent: true },
      { source: '/best-online-food-ordering-software-by-posso-ltd-uk', destination: '/online-food-ordering-software', permanent: true },
      { source: '/best-pizza-delivery-pos-by-posso-ltd-uk', destination: '/pizza-delivery-pos', permanent: true },
      { source: '/best-tablet-epos-system-by-posso-ltd-uk', destination: '/tablet-epos-system', permanent: true },
      { source: '/best-tablet-epos-system-uk-by-posso-ltd-uk', destination: '/tablet-epos-system', permanent: true },
      { source: '/best-restaurant-delivery-system-by-posso-ltd-uk', destination: '/restaurant-delivery-system', permanent: true },
      { source: '/best-portable-epos-systems-by-posso-ltd-uk', destination: '/portable-epos-system', permanent: true },
      { source: '/best-cloud-epos-software-by-posso-ltd-uk', destination: '/cloud-epos-system', permanent: true },
      { source: '/best-cloud-based-epos-systems-uk-by-posso-ltd-uk', destination: '/cloud-epos-system', permanent: true },
      { source: '/best-hospitality-pos-software-by-posso-ltd-uk', destination: '/hospitality-pos-software', permanent: true },
      { source: '/best-self-order-kiosk-fast-food-by-posso-ltd-uk', destination: '/self-order-kiosk-fast-food', permanent: true },
      { source: '/best-touchscreen-pos-system-by-posso-ltd-uk', destination: '/touchscreen-pos-system', permanent: true },
      { source: '/best-touch-screen-pos-software-by-posso-ltd-uk', destination: '/touchscreen-pos-system', permanent: true },
      { source: '/best-free-epos-software-by-posso-ltd-uk', destination: '/free-epos-software', permanent: true },
      { source: '/best-free-epos-software-uk-by-posso-ltd-uk', destination: '/free-epos-software', permanent: true },
      { source: '/best-pub-epos-system-by-posso-ltd-uk', destination: '/pub-epos-system', permanent: true },
      { source: '/best-pub-epos-by-posso-ltd-uk', destination: '/pub-epos-system', permanent: true },
      { source: '/best-golf-club-pos-systems-by-posso-ltd-uk', destination: '/golf-club-pos-system', permanent: true },
      { source: '/best-sweet-shop-pos-by-posso-ltd-uk', destination: '/sweet-shop-pos', permanent: true },
      { source: '/best-sweet-shop-pos-system-by-posso-ltd-uk', destination: '/sweet-shop-pos', permanent: true },
      { source: '/best-salon-point-of-sale-software-by-posso-ltd-uk', destination: '/salon-pos-software', permanent: true },
      { source: '/best-table-service-app-by-posso-ltd-uk', destination: '/restaurant-order-at-table-app', permanent: true },
      { source: '/best-self-ordering-system-by-posso-ltd-uk', destination: '/self-ordering-kiosk', permanent: true },
      { source: '/best-pos-software-by-posso-ltd-uk', destination: '/pos-software', permanent: true },
      { source: '/best-coffee-pos-by-posso-ltd-uk', destination: '/coffee-pos-system', permanent: true },
      { source: '/best-coffee-pos-system-by-posso-ltd-uk', destination: '/coffee-pos-system', permanent: true },
      { source: '/best-pizza-epos-by-posso-ltd-uk', destination: '/pizza-epos', permanent: true },
      { source: '/best-pizza-shop-pos-software-by-posso-ltd-uk', destination: '/pizza-shop-pos', permanent: true },
      { source: '/best-pizza-shop-point-of-sale-by-posso-ltd-uk', destination: '/pizza-shop-pos', permanent: true },
      { source: '/best-bar-ordering-app-by-posso-ltd-uk', destination: '/bar-ordering-app', permanent: true },
      { source: '/best-pos-for-pizza-shop-by-posso-ltd-uk', destination: '/pos-for-pizza-shop', permanent: true },
      { source: '/best-pos-system-for-pizza-shop-by-posso-ltd-uk', destination: '/pos-for-pizza-shop', permanent: true },
      { source: '/best-restaurant-till-by-posso-ltd-uk', destination: '/restaurant-till-system', permanent: true },
      { source: '/best-shop-till-software-by-posso-ltd-uk', destination: '/shop-till-software', permanent: true },
      { source: '/best-app-for-takeaways-by-posso-ltd-uk', destination: '/takeaway-app', permanent: true },
      { source: '/best-food-delivery-order-by-posso-ltd-uk', destination: '/food-delivery-ordering', permanent: true },
      { source: '/best-dry-cleaning-software-by-posso-ltd-uk', destination: '/dry-cleaning-software', permanent: true },
      { source: '/best-spot-dry-cleaning-software-by-posso-ltd-uk', destination: '/dry-cleaning-software', permanent: true },
      { source: '/best-homeware-pos-by-posso-ltd-uk', destination: '/homeware-pos', permanent: true },
      { source: '/best-bespoke-epos-software-by-posso-ltd-uk', destination: '/bespoke-epos-software', permanent: true },
      { source: '/best-bespoke-pos-by-posso-ltd-uk', destination: '/bespoke-epos-software', permanent: true },
      { source: '/best-pdq-machine-for-small-businesses-by-posso-ltd-uk', destination: '/pdq-machine-small-business', permanent: true },
      { source: '/best-pdq-machines-by-posso-ltd-uk', destination: '/pdq-systems', permanent: true },
      { source: '/best-pdq-machines-uk-by-posso-ltd-uk', destination: '/pdq-systems', permanent: true },
      { source: '/best-pdq-systems-by-posso-ltd-uk', destination: '/pdq-systems', permanent: true },
      { source: '/best-order-counter-pos-system-by-posso-ltd-uk', destination: '/order-counter-pos', permanent: true },
      { source: '/best-custom-pos-system-by-posso-ltd-uk', destination: '/custom-pos-system', permanent: true },
      { source: '/best-mobile-pos-system-uk-by-posso-ltd-uk', destination: '/mobile-pos-system-uk', permanent: true },
      { source: '/best-self-service-epos-by-posso-ltd-uk', destination: '/self-service-epos', permanent: true },
      { source: '/best-restaurant-self-ordering-system-by-posso-ltd-uk', destination: '/self-service-epos', permanent: true },
      { source: '/best-till-system-software-by-posso-ltd-uk', destination: '/till-system-software', permanent: true },
      { source: '/best-touch-screen-till-system-by-posso-ltd-uk', destination: '/touch-screen-till-system', permanent: true },
      { source: '/best-touch-screen-epos-system-by-posso-ltd-uk', destination: '/touch-screen-till-system', permanent: true },
      { source: '/best-epos-touchscreen-by-posso-ltd-uk', destination: '/touch-screen-till-system', permanent: true },
      { source: '/best-kiosk-pos-by-posso-ltd-uk', destination: '/kiosk-pos', permanent: true },
      { source: '/best-pos-kiosks-by-posso-ltd-uk', destination: '/kiosk-pos', permanent: true },
      { source: '/best-self-serve-kiosk-by-posso-ltd-uk', destination: '/self-serve-kiosk', permanent: true },
      { source: '/best-uk-kiosk-by-posso-ltd-uk', destination: '/self-serve-kiosk', permanent: true },
      { source: '/best-kiosk-uk-by-posso-ltd-uk', destination: '/self-serve-kiosk', permanent: true },
      { source: '/best-online-ordering-pos-by-posso-ltd-uk', destination: '/online-ordering-pos', permanent: true },
      { source: '/best-delivery-pos-software-by-posso-ltd-uk', destination: '/delivery-pos-software', permanent: true },
      { source: '/best-epos-booking-system-by-posso-ltd-uk', destination: '/epos-booking-system', permanent: true },
      { source: '/best-epos-now-booking-system-by-posso-ltd-uk', destination: '/epos-booking-system', permanent: true },
      { source: '/best-free-restaurant-pos-by-posso-ltd-uk', destination: '/free-restaurant-pos', permanent: true },
      { source: '/best-free-pos-system-by-posso-ltd-uk', destination: '/free-restaurant-pos', permanent: true },
      { source: '/best-epos-software-free-by-posso-ltd-uk', destination: '/free-restaurant-pos', permanent: true },
      { source: '/best-best-free-epos-software-by-posso-ltd-uk', destination: '/free-restaurant-pos', permanent: true },
      { source: '/best-best-epos-system-for-small-grocery-store-by-posso-ltd-uk', destination: '/grocery-store-epos', permanent: true },
      { source: '/best-restaurant-pre-order-app-by-posso-ltd-uk', destination: '/restaurant-pre-order-app', permanent: true },
      { source: '/best-nail-salon-pos-by-posso-ltd-uk', destination: '/nail-salon-pos', permanent: true },
      { source: '/best-nail-salon-pos-software-by-posso-ltd-uk', destination: '/nail-salon-pos', permanent: true },
      { source: '/best-beauty-salon-software-point-of-sale-by-posso-ltd-uk', destination: '/beauty-salon-pos', permanent: true },
      { source: '/best-food-ordering-apps-by-posso-ltd-uk', destination: '/food-ordering-apps', permanent: true },
      { source: '/best-mobile-ordering-apps-by-posso-ltd-uk', destination: '/mobile-ordering-apps', permanent: true },
      { source: '/best-coffee-shop-ordering-app-by-posso-ltd-uk', destination: '/coffee-shop-ordering-app', permanent: true },
      { source: '/best-mobile-ordering-app-for-coffee-shops-by-posso-ltd-uk', destination: '/coffee-shop-ordering-app', permanent: true },
      { source: '/best-digital-signage-systems-by-posso-ltd-uk', destination: '/digital-signage-systems', permanent: true },
      { source: '/best-hospitality-software-uk-by-posso-ltd-uk', destination: '/hospitality-software-uk', permanent: true },
      { source: '/best-pos-hospitality-systems-by-posso-ltd-uk', destination: '/hospitality-software-uk', permanent: true },
      { source: '/best-restaurant-ordering-app-free-uk-by-posso-ltd-uk', destination: '/restaurant-ordering-app', permanent: true },
      { source: '/best-restaurant-order-taking-system-by-posso-ltd-uk', destination: '/restaurant-ordering-app', permanent: true },
      { source: '/best-best-cash-register-for-small-business-uk-by-posso-ltd-uk', destination: '/cash-register-small-business', permanent: true },
      { source: '/best-self-order-app-by-posso-ltd-uk', destination: '/self-order-app', permanent: true },
      { source: '/best-self-order-kiosk-fast-food-by-posso-ltd-uk', destination: '/self-order-kiosk-fast-food', permanent: true },
      { source: '/best-pizza-pos-software-by-posso-ltd-uk', destination: '/pizza-pos-software', permanent: true },
      { source: '/best-pizza-pos-system-by-posso-ltd-uk', destination: '/pizza-pos-software', permanent: true },
      { source: '/best-best-pizza-pos-by-posso-ltd-uk', destination: '/pizza-pos-software', permanent: true },
      { source: '/best-best-pizza-pos-system-2020-by-posso-ltd-uk', destination: '/pizza-pos-software', permanent: true },
      { source: '/best-pizza-restaurant-software-by-posso-ltd-uk', destination: '/pizza-restaurant-software', permanent: true },
      { source: '/best-easy-pos-system-by-posso-ltd-uk', destination: '/easy-pos-system', permanent: true },
      { source: '/best-pos-machine-software-by-posso-ltd-uk', destination: '/pos-machine-software', permanent: true },
      { source: '/best-food-ordering-machine-by-posso-ltd-uk', destination: '/food-ordering-machine', permanent: true },
      { source: '/best-tablet-food-ordering-system-by-posso-ltd-uk', destination: '/tablet-food-ordering-system', permanent: true },
      { source: '/best-online-food-ordering-portal-by-posso-ltd-uk', destination: '/online-food-ordering-portal', permanent: true },
      { source: '/best-web-based-ordering-system-for-coffee-shops-by-posso-ltd-uk', destination: '/web-based-ordering-system-coffee-shops', permanent: true },
      { source: '/best-online-ordering-software-for-coffee-shops-by-posso-ltd-uk', destination: '/online-ordering-software-coffee-shops', permanent: true },
      { source: '/best-mobile-ordering-system-for-coffee-shops-by-posso-ltd-uk', destination: '/mobile-ordering-system-coffee-shops', permanent: true },
      { source: '/best-online-ordering-platform-for-coffee-shops-by-posso-ltd-uk', destination: '/online-ordering-platform-coffee-shops', permanent: true },
      { source: '/best-mobile-ordering-platform-for-coffee-shops-by-posso-ltd-uk', destination: '/mobile-ordering-platform-coffee-shops', permanent: true },
      { source: '/best-cafe-online-ordering-system-by-posso-ltd-uk', destination: '/cafe-online-ordering-system', permanent: true },
      { source: '/best-text-ordering-system-by-posso-ltd-uk', destination: '/text-ordering-system', permanent: true },
      { source: '/best-pos-signage-by-posso-ltd-uk', destination: '/pos-signage', permanent: true },
      { source: '/best-food-and-drink-digital-signage-by-posso-ltd-uk', destination: '/food-and-drink-digital-signage', permanent: true },
      { source: '/best-epos-credit-card-application-by-posso-ltd-uk', destination: '/epos-credit-card-application', permanent: true },
      { source: '/best-self-employed-card-machine-by-posso-ltd-uk', destination: '/self-employed-card-machine', permanent: true },
      { source: '/best-free-card-machine-by-posso-ltd-uk', destination: '/free-card-machine', permanent: true },
      { source: '/best-cheap-epos-software-by-posso-ltd-uk', destination: '/cheap-epos-software', permanent: true },
      { source: '/best-cheap-epos-by-posso-ltd-uk', destination: '/cheap-epos-software', permanent: true },
      { source: '/best-cheap-pos-system-by-posso-ltd-uk', destination: '/cheap-epos-software', permanent: true },
      { source: '/best-cheap-epos-system-by-posso-ltd-uk', destination: '/cheap-epos-software', permanent: true },
      { source: '/best-best-pos-for-pizza-delivery-by-posso-ltd-uk', destination: '/pizza-delivery-pos', permanent: true },
      { source: '/best-best-pos-system-for-pizza-shop-by-posso-ltd-uk', destination: '/pos-for-pizza-shop', permanent: true },
      { source: '/best-restaurant-self-ordering-system-by-posso-ltd-uk', destination: '/restaurant-self-ordering-system', permanent: true },
      { source: '/best-hospitality-kiosks-by-posso-ltd-uk', destination: '/hospitality-kiosks', permanent: true },
      { source: '/best-pos-webshop-by-posso-ltd-uk', destination: '/pos-webshop', permanent: true },
      { source: '/best-pos-companies-uk-by-posso-ltd-uk', destination: '/pos-companies-uk', permanent: true },
      { source: '/best-buy-epos-system-uk-by-posso-ltd-uk', destination: '/buy-epos-system-uk', permanent: true },
      { source: '/best-food-to-order-online-by-posso-ltd-uk', destination: '/food-to-order-online', permanent: true },
      { source: '/best-open-source-epos-software-by-posso-ltd-uk', destination: '/open-source-epos-software', permanent: true },
      { source: '/best-diy-pos-system-restaurants-by-posso-ltd-uk', destination: '/diy-pos-system-restaurants', permanent: true },
      { source: '/best-build-your-own-pos-system-by-posso-ltd-uk', destination: '/build-your-own-pos-system', permanent: true },
      { source: '/best-website-pos-finance-software-by-posso-ltd-uk', destination: '/website-pos-finance-software', permanent: true },
      { source: '/best-epos-marketing-by-posso-ltd-uk', destination: '/epos-marketing', permanent: true },
      { source: '/best-epos-portal-by-posso-ltd-uk', destination: '/epos-portal', permanent: true },
      { source: '/best-takeaway-pos-by-posso-ltd-uk', destination: '/takeaway-pos', permanent: true },
      { source: '/best-restaurant-software-free-download-full-version-by-posso-ltd-uk', destination: '/restaurant-software-free', permanent: true },
      { source: '/best-pos-for-sweet-shop-by-posso-ltd-uk', destination: '/pos-for-sweet-shop', permanent: true },
      { source: '/best-pos-software-for-sweet-shop-by-posso-ltd-uk', destination: '/pos-for-sweet-shop', permanent: true },
      { source: '/best-sweet-shop-point-of-sale-software-by-posso-ltd-uk', destination: '/sweet-shop-point-of-sale', permanent: true },
      { source: '/best-diy-cash-drawer-by-posso-ltd-uk', destination: '/diy-cash-drawer', permanent: true },
      { source: '/best-self-serve-coffee-bar-stands-by-posso-ltd-uk', destination: '/self-serve-coffee-bar', permanent: true },
      { source: '/best-branded-self-serve-coffee-cart-by-posso-ltd-uk', destination: '/branded-self-serve-coffee-cart', permanent: true },
      { source: '/best-facebook-food-ordering-system-by-posso-ltd-uk', destination: '/facebook-food-ordering-system', permanent: true },
      { source: '/best-takeaway-software-uk-by-posso-ltd-uk', destination: '/epos-software-for-takeaway', permanent: true },
      { source: '/epos-system-for-takeaways', destination: '/epos-systems-for-takeaways', permanent: true },
      { source: '/restaurant-epos-system-3', destination: '/pos', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
          { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
        ],
      },
    ];
  },
};

export default nextConfig;
