import { MetadataRoute } from 'next';

const URL = 'https://posso.uk';

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    '/',
    '/pos',
    '/kiosks',
    '/ticketing',
    '/digital-signage',
    '/credit-card-machines',
    '/credit-card-machines-enquiry',
    '/teya-card-machine-application-form',
    '/franchise',
    '/online-ordering',
    '/shop-fitting',
    '/shop-signage',
    '/finance',
    '/contact',
    '/blog',
    '/blog/pos-systems-for-restaurants-and-takeaways',
    '/blog/self-order-kiosks',
    '/blog/online-ordering-and-mobile-apps',
    '/blog/best-card-machine-for-small-business',
    '/blog/self-service-revolution',
    '/blog/why-posso-amusement-park-efficiency-2026',
    '/blog/why-posso-trampoline-park-tech-stack',
    '/blog/why-posso-ice-rink-management-software',
    '/blog/benefits-of-a-mobile-pos-device-for-restaurants',
    '/blog/best-food-delivery-app-uk',
    '/blog/pos-for-pizza-restaurant-best-system-for-pizza-shops',
    '/blog/cafe-coffee-shop-epos-systems-uk',
    '/agents',
    '/privacy-policy',
    '/cookie-policy',
    '/software-terms',
    '/solutions/trampoline-parks',
    '/solutions/family-entertainment-centers',
    '/solutions/amusement-parks',
    '/solutions/water-parks',
    '/solutions/museums',
    '/solutions/zoos-aquariums',
    '/solutions/wake-parks',
    '/solutions/rock-climbing-gyms',
    '/solutions/playcenters-softplay',
    '/solutions/roller-skating-rinks',
    '/solutions/ice-skating-rinks',
    '/solutions/ski-resorts',
    '/solutions/spas-wellness-centers',
    '/solutions/festivals-events',
    '/web-design',
    '/digital-menu-boards-uk-my-signage',
    '/contact-posso-ltd',
    '/self-order-kiosk-uk-2',
    '/self-order-kiosks-uk',
    '/book-a-call',
    '/credit-card-machine-clover-flex-uk',
    '/digital-menu-boards-4',
    '/hospitality-epos-systems-by-posso-uk-epos-systems',
    '/food-order-app-comparison-tool',
    '/restaurant-epos-system-3',
    '/android-epos-systems-from-posso',
    '/small-pos-magic-the-tiny-marvels-transforming-our-lives',
    '/dry-cleaning-epos-systems-uk',
    '/portable-card-machines',
    '/skegness-pos-systems',
    '/cobways-tell-a-friend-scheme',
    '/franchise-epos',
    '/posso-epos'
  ];

  return routes.map((route) => ({
    url: `${URL}${route}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'monthly',
    priority: route === '/' ? 1 : 0.8,
  }));
}
