import { MetadataRoute } from 'next';
import { getAllSlugs } from '@/lib/seo-pages-data';

const URL = 'https://posso.co.uk';

export default function sitemap(): MetadataRoute.Sitemap {
  // SEO landing pages (programmatic)
  const seoPageRoutes = getAllSlugs().map(slug => `/${slug}`);

  const routes = [
    '/',
    '/pos',
    '/kiosks',
    '/ticketing',
    '/digital-signage',
    '/credit-card-machines',
    '/credit-card-machines-enquiry',
    '/teya-card-machine-application-form',
    '/franchise',
    '/online-ordering',
    '/shop-fitting',
    '/shop-signage',
    '/finance',
    '/contact',
    '/blog',
    '/blog/pos-systems-for-restaurants-and-takeaways',
    '/blog/self-order-kiosks',
    '/blog/online-ordering-and-mobile-apps',
    '/blog/best-card-machine-for-small-business',
    '/blog/self-service-revolution',
    '/blog/why-posso-amusement-park-efficiency-2026',
    '/blog/why-posso-trampoline-park-tech-stack',
    '/blog/why-posso-ice-rink-management-software',
    '/blog/benefits-of-a-mobile-pos-device-for-restaurants',
    '/blog/best-food-delivery-app-uk',
    '/blog/pos-for-pizza-restaurant-best-system-for-pizza-shops',
    '/blog/cafe-coffee-shop-epos-systems-uk',
    '/blog/pos-and-self-order-kiosk-solutions',
    '/blog/free-epos-software-uk-truth',
    '/blog/portable-card-machine-hospitality',
    '/blog/posso-future-hospitality-tech',
    '/blog/epos-system-for-indian-takeaway',
    '/blog/epos-software-for-takeaway-orders',
    '/blog/epos-system-for-takeaway-commission-free',
    '/blog/cafe-pos-system-efficiency',
    '/blog/restaurant-epos-table-management',
    '/blog/best-pos-system-for-pizza-delivery',
    '/blog/hybrid-epos-systems-for-takeaways',
    '/agents',
    '/privacy-policy',
    '/cookie-policy',
    '/software-terms',
    '/solutions/trampoline-parks',
    '/solutions/family-entertainment-centers',
    '/solutions/amusement-parks',
    '/solutions/water-parks',
    '/solutions/museums',
    '/solutions/zoos-aquariums',
    '/solutions/wake-parks',
    '/solutions/rock-climbing-gyms',
    '/solutions/playcenters-softplay',
    '/solutions/roller-skating-rinks',
    '/solutions/ice-skating-rinks',
    '/solutions/ski-resorts',
    '/solutions/spas-wellness-centers',
    '/solutions/festivals-events',
    '/solutions/restaurant-self-service-kiosk',
    '/solutions/kiosks-for-retail',
    '/solutions/franchise-pos-systems',
    '/solutions/self-service-kiosk-uk',
    '/web-design',
    '/digital-menu-boards-uk-my-signage',
    '/contact-posso-ltd',
    '/self-order-kiosk-uk-2',
    '/self-order-kiosks-uk',
    '/book-a-call',
    '/credit-card-machine-clover-flex-uk',
    '/digital-menu-boards-4',
    '/hospitality-epos-systems-by-posso-uk-epos-systems',
    '/food-order-app-comparison-tool',
    '/restaurant-epos-system-3',
    '/android-epos-systems-from-posso',
    '/small-pos-magic-the-tiny-marvels-transforming-our-lives',
    '/dry-cleaning-epos-systems-uk',
    '/solutions/dry-cleaning-pos-system',
    '/portable-card-machines',
    '/skegness-pos-systems',
    '/cobways-tell-a-friend-scheme',
    '/franchise-epos',
    '/posso-epos',
    '/pos-systems'
  ];

  const allRoutes = [...routes, ...seoPageRoutes];

  return allRoutes.map((route) => ({
    url: `${URL}${route}`,
    lastModified: new Date().toISOString(),
    changeFrequency: 'monthly' as const,
    priority: route === '/' ? 1 : 0.8,
  }));
}
